# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Title (appears only in the PDF properties)
#+AUTHOR: Lucas Mello Schnorr

#+STARTUP: overview indent
#+LANGUAGE: pt-br
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_CLASS: ACMART
#+LATEX_CLASS_OPTIONS: [format=acmsmall, review=false, screen=true]
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}

# You need at least Org 9 and Emacs 24 to make this work.
# If you do, just type make (thanks Luka Stanisic for this).
# You'll also need to install texlive-publishers to get acmart.cls

* ACM-SMALL configuration for org export + ignore tag (Start Here) :noexport:

#+begin_src emacs-lisp :results output :session :exports both
(add-to-list 'load-path ".")
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
(add-to-list 'org-latex-classes
             '("ACMART"
               "\\documentclass{acmart}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

#+RESULTS:

* *The Paper*                                                       :ignore:
** Latex configurations                                             :ignore:
#+BEGIN_EXPORT latex
% Metadata Information
\acmJournal{TOMPECS}
\acmVolume{9}
\acmNumber{4}
\acmArticle{39}
\acmYear{2010}
\acmMonth{3}
\copyrightyear{2009}
%\acmArticleSeq{9}

% Copyright
%\setcopyright{acmcopyright}
\setcopyright{acmlicensed}
%\setcopyright{rightsretained}
%\setcopyright{usgov}
%\setcopyright{usgovmixed}
%\setcopyright{cagov}
%\setcopyright{cagovmixed}

% DOI
\acmDOI{0000001.0000001}

% Paper history
\received{February 2007}
\received[revised]{March 2009}
\received[accepted]{June 2009}
#+END_EXPORT
** Frontpage                                                        :ignore:
#+BEGIN_EXPORT latex
\title[Small Title]{This is the Real Title}

\author{Lucas Mello Schnorr}
\orcid{0000-0003-4828-9942}
\affiliation{%
  \institution{Universidade Federal do Rio Grande do Sul}
  \streetaddress{Campus do Vale - Sector 4 - Building 43425}
  \city{Porto Alegre}
  \state{RS}
  \postcode{91501-970}
  \country{Brazil}}

\author{Somebody Else}
\affiliation{%
  \institution{Somebody Else's Institution}
  \city{Paris}
  \country{France}
}
#+END_EXPORT

*** Abstract                                                       :ignore:

#+LaTeX: \begin{abstract}

Put the abstract here.

#+LaTeX: \end{abstract}

*** ACM Code Classification                                        :ignore:
#+BEGIN_EXPORT latex
%
% The code below should be generated by the tool at
% http://dl.acm.org/ccs.cfm
% Please copy and paste the code instead of the example below. 
%
\begin{CCSXML}
<ccs2012>
 <concept>
  <concept_id>10010520.10010553.10010562</concept_id>
  <concept_desc>Computer systems organization~Embedded systems</concept_desc>
  <concept_significance>500</concept_significance>
 </concept>
 <concept>
  <concept_id>10010520.10010575.10010755</concept_id>
  <concept_desc>Computer systems organization~Redundancy</concept_desc>
  <concept_significance>300</concept_significance>
 </concept>
 <concept>
  <concept_id>10010520.10010553.10010554</concept_id>
  <concept_desc>Computer systems organization~Robotics</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
 <concept>
  <concept_id>10003033.10003083.10003095</concept_id>
  <concept_desc>Networks~Network reliability</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
</ccs2012>  
\end{CCSXML}

\ccsdesc[500]{Computer systems organization~Embedded systems}
\ccsdesc[300]{Computer systems organization~Redundancy}
\ccsdesc{Computer systems organization~Robotics}
\ccsdesc[100]{Networks~Network reliability}

%
% End generated code
%

#+END_EXPORT

*** Keywords, thanks                                               :ignore:
#+BEGIN_EXPORT latex
\keywords{Keyword 1, Keyword 2}
\thanks{This work is supported by ...}
#+END_EXPORT
*** Maketitle                                                      :ignore:
#+LaTeX: \maketitle
** Introduction

This is just an example to show how Orgmode\cite{orgmode} can be
neatly used to write papers following the ACM latex style. Feel
free to modify and distributed this as you wish.

Be aware that this example is compatible with OrgMode 9.*. Earlier
or later OrgMode versions require minor modifications to the Makefile
and/or llncs.org files.

For a detailed explanation on why and how to write reproducible
articles using OrgMode, please visit the following [[https://github.com/alegrand/RR_webinars/blob/master/1_replicable_article_laboratory_notebook/index.org][page]].

** Background and Experimental Context
\label{sec.context}
*** Background
\label{sec.background}
*** Experimental Context and Workload Details
\label{sec.setup}
** Related Work and Motivation
\label{sec.relatedwork}

Check this paper\cite{schnorr2013visualizing} about how you need to
semantically aggregate data.

** Your Great Contribution to Computer Science
\label{sec.proposal}
** Your Super Results
** Conclusion
** Acknowledgments                                                  :ignore:

#+LATEX:\section*{Acknowledgements}

Who paid for this?

** References                                                        :ignore:

# See next section to understand how refs.bib file is created.

#+LATEX: \bibliographystyle{ACM-Reference-Format}
#+LATEX: \bibliography{refs}

* Bib file is here                                                 :noexport:

Tangle this file with C-c C-v t

#+begin_src bib :tangle refs.bib
@article{orgmode,
  author =	"Eric Schulte and Dan Davison and Thomas Dye and Carsten Dominik",
  title =	"A Multi-Language Computing Environment for Literate Programming and Reproducible Research",
  journal =	"J. of Stat. Soft.",
  volume =	"46",
  number =	"3",
  day =  	"25",
  year = 	"2012",
  CODEN =	"JSSOBK",
  ISSN = 	"1548-7660",
  bibdate =	"2011-10-03",
  accepted =	"2011-10-03",
  acknowledgement = "",
  submitted =	"2010-12-22",
}

@incollection{schnorr2013visualizing,
  title={Visualizing More Performance Data Than What Fits on Your Screen},
  author={Schnorr, Lucas M and Legrand, Arnaud},
  booktitle={Tools for High Performance Computing 2012},
  pages={149--162},
  year={2013},
  publisher={Springer}
}


#+end_src
* Emacs setup                                                      :noexport:
# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (ox-extras-activate '(ignore-headlines))
# eval: (add-to-list 'org-latex-classes '("ACMART" "\\documentclass{acmart}" ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection{%s}" . "\\subsubsection*{%s}") ("\\paragraph{%s}" . "\\paragraph*{%s}") ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:
